import type { ThemeMap } from '../types';

// Cheatsheet Style Themes
// Each theme defines custom CSS variables and specific Markdown element styles

export const themes: ThemeMap = {
    classic: {
        name: 'Classic',
        description: 'Traditional black & white with clean typography',
        cssVars: {
            '--theme-bg': '#ffffff',
            '--theme-text': '#1a1a1a',
            '--theme-heading': '#000000',
            '--theme-accent': '#0066cc',
            '--theme-border': '#ddd',
            '--theme-code-bg': '#f8f8f8',
            '--theme-code-text': '#c7254e',
            '--theme-quote-border': '#666',
            '--theme-table-striped': '#f9f9f9',
        },
        styles: {
            h1: {
                fontSize: '1.8em',
                fontWeight: '700',
                borderBottom: '2px solid #333',
                paddingBottom: '0.2em',
                margin: '0.5em 0 0.3em 0',
            },
            h2: {
                fontSize: '1.4em',
                fontWeight: '600',
                borderBottom: '1px solid #666',
                paddingBottom: '0.15em',
                margin: '0.4em 0 0.25em 0',
            },
            h3: {
                fontSize: '1.2em',
                fontWeight: '600',
                margin: '0.3em 0 0.2em 0',
            },
            h4: {
                fontSize: '1.1em',
                fontWeight: '600',
                margin: '0.25em 0 0.15em 0',
            },
            codeInline: {
                background: '#f8f8f8',
                color: '#c7254e',
                padding: '0 0.4em',
                borderRadius: '3px',
                boxShadow: 'inset 0 0 0 1px #e0e0e0',
                fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                fontSize: '0.85em',
            },
            codeBlock: {
                background: '#f8f8f8',
                border: '1px solid #ddd',
                borderRadius: '4px',
            },
            link: {
                color: '#0066cc',
                textDecoration: 'none',
                borderBottom: '1px dotted #0066cc',
            },
            blockquote: {
                borderLeft: '3px solid #666',
                color: '#555',
                fontStyle: 'italic',
            },
            strong: {
                fontWeight: '700',
            },
            table: {
                borderColor: '#ddd',
                headerBg: '#f0f0f0',
                headerColor: '#1a1a1a',
                headerFontWeight: '600',
                stripedBg: '#f9f9f9',
                cellBorder: '1px solid #ddd',
            },
        },
    },

    modern: {
        name: 'Modern',
        description: 'Vibrant gradients with bold typography',
        cssVars: {
            '--theme-bg': '#ffffff',
            '--theme-text': '#1e293b',
            '--theme-heading': '#0f172a',
            '--theme-accent': '#3b82f6',
            '--theme-accent-2': '#8b5cf6',
            '--theme-border': '#e2e8f0',
            '--theme-code-bg': '#f1f5f9',
            '--theme-code-text': '#db2777',
            '--theme-quote-border': '#3b82f6',
            '--theme-table-striped': '#f8fafc',
        },
        styles: {
            h1: {
                fontSize: '2em',
                fontWeight: '800',
                background: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
                margin: '0.5em 0 0.3em 0',
                borderBottom: '3px solid transparent',
                borderImage: 'linear-gradient(90deg, #3b82f6, #8b5cf6)',
                borderImageSlice: '1',
            },
            h2: {
                fontSize: '1.5em',
                fontWeight: '700',
                color: '#3b82f6',
                margin: '0.4em 0 0.25em 0',
                borderLeft: '4px solid #3b82f6',
                paddingLeft: '0.5em',
            },
            h3: {
                fontSize: '1.25em',
                fontWeight: '600',
                color: '#8b5cf6',
                margin: '0.3em 0 0.2em 0',
            },
            h4: {
                fontSize: '1.1em',
                fontWeight: '600',
                color: '#3b82f6',
                margin: '0.25em 0 0.15em 0',
            },
            codeInline: {
                background: '#f1f5f9',
                color: '#db2777',
                padding: '0 0.4em',
                borderRadius: '4px',
                fontWeight: '500',
                fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                fontSize: '0.85em',
            },
            codeBlock: {
                background: '#f1f5f9',
                border: '2px solid #e2e8f0',
                borderRadius: '8px',
                boxShadow: '0 2px 8px rgba(59, 130, 246, 0.1)',
            },
            link: {
                color: '#3b82f6',
                fontWeight: '500',
                textDecoration: 'none',
                borderBottom: '2px solid #3b82f6',
            },
            blockquote: {
                borderLeft: '4px solid #3b82f6',
                paddingLeft: '0.8em',
                color: '#475569',
                background: 'linear-gradient(90deg, #eff6ff 0%, transparent 100%)',
                padding: '0.5em 0.8em',
                borderRadius: '0 4px 4px 0',
            },
            strong: {
                fontWeight: '700',
                color: '#0f172a',
            },
            paragraph: {
                color: '#1e293b',
            },
            table: {
                borderColor: '#e2e8f0',
                headerBg: 'linear-gradient(135deg, #eff6ff 0%, #f5f3ff 100%)',
                headerColor: '#1e293b',
                headerFontWeight: '700',
                stripedBg: '#f8fafc',
                cellBorder: '1px solid #e2e8f0',
            },
        },
    },

    minimal: {
        name: 'Minimal',
        description: 'Clean and spacious with subtle accents',
        cssVars: {
            '--theme-bg': '#ffffff',
            '--theme-text': '#374151',
            '--theme-heading': '#111827',
            '--theme-accent': '#10b981',
            '--theme-border': '#e5e7eb',
            '--theme-code-bg': '#f9fafb',
            '--theme-code-text': '#059669',
            '--theme-quote-border': '#d1d5db',
            '--theme-table-striped': '#fafafa',
        },
        styles: {
            h1: {
                fontSize: '1.75em',
                fontWeight: '300',
                color: '#111827',
                letterSpacing: '-0.02em',
                margin: '0.6em 0 0.4em 0',
                borderBottom: 'none',
            },
            h2: {
                fontSize: '1.35em',
                fontWeight: '400',
                color: '#1f2937',
                margin: '0.5em 0 0.3em 0',
                borderBottom: '1px solid #f3f4f6',
                paddingBottom: '0.3em',
            },
            h3: {
                fontSize: '1.15em',
                fontWeight: '500',
                color: '#374151',
                margin: '0.4em 0 0.2em 0',
            },
            h4: {
                fontSize: '1.05em',
                fontWeight: '500',
                color: '#4b5563',
                margin: '0.3em 0 0.15em 0',
            },
            codeInline: {
                background: '#f9fafb',
                color: '#059669',
                padding: '0 0.4em',
                borderRadius: '2px',
                fontSize: '0.85em',
                fontFamily: "'JetBrains Mono', 'Courier New', monospace",
            },
            codeBlock: {
                background: '#f9fafb',
                border: '1px solid #e5e7eb',
                borderRadius: '6px',
            },
            link: {
                color: '#10b981',
                textDecoration: 'none',
                borderBottom: '1px solid transparent',
            },
            blockquote: {
                borderLeft: '2px solid #d1d5db',
                paddingLeft: '0.8em',
                color: '#6b7280',
                fontStyle: 'normal',
            },
            strong: {
                fontWeight: '700',
                color: '#111827',
            },
            paragraph: {
                color: '#374151',
            },
            table: {
                borderColor: '#e5e7eb',
                headerBg: '#f9fafb',
                headerColor: '#111827',
                headerFontWeight: '500',
                stripedBg: '#fafafa',
                cellBorder: '1px solid #e5e7eb',
            },
        },
    },

    dark: {
        name: 'Dark',
        description: 'Pure black & white dark mode',
        cssVars: {
            '--theme-bg': '#1a1a1a',
            '--theme-text': '#e5e5e5',
            '--theme-heading': '#ffffff',
            '--theme-accent': '#ffffff',
            '--theme-border': '#404040',
            '--theme-code-bg': '#2a2a2a',
            '--theme-code-text': '#e5e5e5',
            '--theme-quote-border': '#606060',
            '--theme-table-striped': '#242424',
        },
        styles: {
            h1: {
                fontSize: '1.9em',
                fontWeight: '700',
                color: '#ffffff',
                margin: '0.5em 0 0.3em 0',
                borderBottom: '2px solid #606060',
                paddingBottom: '0.2em',
            },
            h2: {
                fontSize: '1.45em',
                fontWeight: '600',
                color: '#ffffff',
                margin: '0.4em 0 0.25em 0',
                borderBottom: '1px solid #404040',
                paddingBottom: '0.15em',
            },
            h3: {
                fontSize: '1.2em',
                fontWeight: '600',
                color: '#f5f5f5',
                margin: '0.3em 0 0.2em 0',
            },
            h4: {
                fontSize: '1.1em',
                fontWeight: '600',
                color: '#e5e5e5',
                margin: '0.25em 0 0.15em 0',
            },
            codeInline: {
                background: '#2a2a2a',
                color: '#e5e5e5',
                padding: '0 0.4em',
                borderRadius: '3px',
                boxShadow: 'inset 0 0 0 1px #404040',
                fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                fontSize: '0.85em',
            },
            codeBlock: {
                background: '#2a2a2a',
                border: '1px solid #404040',
                borderRadius: '6px',
                textShadow: 'none',
            },
            link: {
                color: '#ffffff',
                textDecoration: 'none',
                borderBottom: '1px solid #808080',
            },
            blockquote: {
                borderLeft: '3px solid #606060',
                paddingLeft: '0.8em',
                color: '#d0d0d0',
                fontStyle: 'italic',
            },
            strong: {
                fontWeight: '700',
                color: '#ffffff',
            },
            paragraph: {
                color: '#e5e5e5',
            },
            table: {
                borderColor: '#404040',
                headerBg: '#2a2a2a',
                headerColor: '#ffffff',
                headerFontWeight: '600',
                stripedBg: '#242424',
                cellBorder: '1px solid #404040',
                cellColor: '#e5e5e5',
            },
        },
    },

    colorful: {
        name: 'Colorful',
        description: 'Bright and playful with rainbow accents',
        cssVars: {
            '--theme-bg': '#ffffff',
            '--theme-text': '#1f2937',
            '--theme-heading': '#111827',
            '--theme-accent': '#f59e0b',
            '--theme-border': '#fde68a',
            '--theme-code-bg': '#fef3c7',
            '--theme-code-text': '#dc2626',
            '--theme-quote-border': '#f59e0b',
            '--theme-table-striped': '#fffbeb',
        },
        styles: {
            h1: {
                fontSize: '1.9em',
                fontWeight: '800',
                background: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 50%, #ec4899 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
                margin: '0.5em 0 0.3em 0',
                borderBottom: '3px solid #fbbf24',
            },
            h2: {
                fontSize: '1.5em',
                fontWeight: '700',
                color: '#7c3aed',
                margin: '0.4em 0 0.25em 0',
                borderLeft: '5px solid #a78bfa',
                paddingLeft: '0.5em',
                background: 'linear-gradient(90deg, #f3e8ff 0%, transparent 100%)',
            },
            h3: {
                fontSize: '1.25em',
                fontWeight: '600',
                color: '#059669',
                margin: '0.3em 0 0.2em 0',
            },
            h4: {
                fontSize: '1.1em',
                fontWeight: '600',
                color: '#dc2626',
                margin: '0.25em 0 0.15em 0',
            },
            codeInline: {
                background: '#fef3c7',
                color: '#dc2626',
                padding: '0 0.4em',
                borderRadius: '4px',
                fontWeight: '600',
                boxShadow: 'inset 0 0 0 1px #fde68a',
                fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                fontSize: '0.85em',
            },
            codeBlock: {
                background: '#fef3c7',
                border: '2px solid #fbbf24',
                borderRadius: '8px',
            },
            link: {
                color: '#2563eb',
                fontWeight: '600',
                textDecoration: 'none',
                borderBottom: '2px solid #60a5fa',
            },
            blockquote: {
                borderLeft: '4px solid #f59e0b',
                paddingLeft: '0.8em',
                color: '#92400e',
                background: 'linear-gradient(90deg, #fef3c7 0%, transparent 100%)',
                padding: '0.5em 0.8em',
                borderRadius: '0 4px 4px 0',
            },
            strong: {
                fontWeight: '800',
                color: '#dc2626',
            },
            paragraph: {
                color: '#1f2937',
            },
            table: {
                borderColor: '#fde68a',
                headerBg: 'linear-gradient(135deg, #fef3c7 0%, #ddd6fe 100%)',
                headerColor: '#1f2937',
                headerFontWeight: '700',
                stripedBg: '#fffbeb',
                cellBorder: '2px solid #fde68a',
            },
        },
    },

    academic: {
        name: 'Academic',
        description: 'Professional serif fonts with traditional styling',
        cssVars: {
            '--theme-bg': '#fefefe',
            '--theme-text': '#2d3748',
            '--theme-heading': '#1a202c',
            '--theme-accent': '#2c5282',
            '--theme-border': '#cbd5e0',
            '--theme-code-bg': '#edf2f7',
            '--theme-code-text': '#744210',
            '--theme-quote-border': '#a0aec0',
            '--theme-table-striped': '#f7fafc',
        },
        styles: {
            h1: {
                fontSize: '1.8em',
                fontWeight: '700',
                color: '#1a202c',
                margin: '0.6em 0 0.4em 0',
                borderBottom: '2px double #2d3748',
                paddingBottom: '0.3em',
                fontFamily: 'Georgia, serif',
                textAlign: 'center',
            },
            h2: {
                fontSize: '1.4em',
                fontWeight: '600',
                color: '#2c5282',
                margin: '0.5em 0 0.3em 0',
                fontFamily: 'Georgia, serif',
            },
            h3: {
                fontSize: '1.2em',
                fontWeight: '600',
                color: '#2d3748',
                margin: '0.4em 0 0.2em 0',
                fontFamily: 'Georgia, serif',
                fontStyle: 'italic',
            },
            h4: {
                fontSize: '1.1em',
                fontWeight: '600',
                color: '#4a5568',
                margin: '0.3em 0 0.15em 0',
                fontFamily: 'Georgia, serif',
            },
            codeInline: {
                background: '#edf2f7',
                color: '#744210',
                padding: '0 0.4em',
                borderRadius: '2px',
                fontFamily: 'Courier New, monospace',
                fontSize: '0.85em',
            },
            codeBlock: {
                background: '#edf2f7',
                border: '1px solid #cbd5e0',
                borderRadius: '4px',
            },
            link: {
                color: '#2c5282',
                textDecoration: 'underline',
                borderBottom: 'none',
            },
            blockquote: {
                borderLeft: '3px solid #a0aec0',
                paddingLeft: '0.8em',
                color: '#4a5568',
                fontStyle: 'italic',
                fontFamily: 'Georgia, serif',
            },
            strong: {
                fontWeight: '700',
                color: '#1a202c',
            },
            paragraph: {
                color: '#2d3748',
            },
            table: {
                borderColor: '#cbd5e0',
                headerBg: '#e2e8f0',
                headerColor: '#1a202c',
                headerFontWeight: '700',
                stripedBg: '#f7fafc',
                cellBorder: '1px solid #cbd5e0',
            },
        },
    },

    neon: {
        name: 'Neon',
        description: 'Cyberpunk-inspired with glowing effects',
        cssVars: {
            '--theme-bg': '#0a0a0a',
            '--theme-text': '#e0e0e0',
            '--theme-heading': '#ffffff',
            '--theme-accent': '#00ff9f',
            '--theme-accent-2': '#00d4ff',
            '--theme-border': '#00ff9f',
            '--theme-code-bg': '#1a1a1a',
            '--theme-code-text': '#ff006e',
            '--theme-quote-border': '#00ff9f',
            '--theme-table-striped': '#0f0f0f',
        },
        styles: {
            h1: {
                fontSize: '2em',
                fontWeight: '900',
                color: '#00ff9f',
                margin: '0.5em 0 0.3em 0',
                textShadow: '0 0 10px #00ff9f, 0 0 20px #00ff9f, 0 0 30px #00ff9f',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
            },
            h2: {
                fontSize: '1.5em',
                fontWeight: '700',
                color: '#00d4ff',
                margin: '0.4em 0 0.25em 0',
                textShadow: '0 0 8px #00d4ff, 0 0 15px #00d4ff',
                borderLeft: '3px solid #00d4ff',
                paddingLeft: '0.5em',
                boxShadow: '-3px 0 10px rgba(0, 212, 255, 0.3)',
            },
            h3: {
                fontSize: '1.25em',
                fontWeight: '600',
                color: '#ff006e',
                margin: '0.3em 0 0.2em 0',
                textShadow: '0 0 5px #ff006e',
            },
            h4: {
                fontSize: '1.1em',
                fontWeight: '600',
                color: '#00ff9f',
                margin: '0.25em 0 0.15em 0',
                textShadow: '0 0 5px #00ff9f',
            },
            codeInline: {
                background: '#1a1a1a',
                color: '#ff006e',
                padding: '0 0.4em',
                borderRadius: '3px',
                boxShadow: 'inset 0 0 0 1px #00ff9f, 0 0 3px rgba(0, 255, 159, 0.3)',
                fontFamily: "'JetBrains Mono', 'Courier New', monospace",
                fontSize: '0.85em',
            },
            codeBlock: {
                background: '#1a1a1a',
                border: '1px solid #00ff9f',
                borderRadius: '6px',
                boxShadow: '0 0 10px rgba(0, 255, 159, 0.2)',
                textShadow: 'none',
            },
            link: {
                color: '#00d4ff',
                textDecoration: 'none',
                borderBottom: '1px solid #00d4ff',
                textShadow: '0 0 5px #00d4ff',
            },
            blockquote: {
                borderLeft: '3px solid #00ff9f',
                paddingLeft: '0.8em',
                color: '#e0e0e0',
                fontStyle: 'italic',
                boxShadow: '-3px 0 10px rgba(0, 255, 159, 0.2)',
            },
            strong: {
                fontWeight: '700',
                color: '#00ff9f',
            },
            paragraph: {
                color: '#e0e0e0',
            },
            table: {
                borderColor: '#00ff9f',
                headerBg: '#1a1a1a',
                headerColor: '#00ff9f',
                headerFontWeight: '700',
                headerTextShadow: '0 0 5px #00ff9f',
                stripedBg: '#0f0f0f',
                cellBorder: '1px solid #00ff9f',
                boxShadow: '0 0 15px rgba(0, 255, 159, 0.1)',
                cellColor: '#e0e0e0',
            },
        },
    },
};

export default themes;
